baseURL = "/"
languageCode = "en-us"
title = "kbh kærlighed"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "neighborhoods"
    url = "/neighborhoods/"
    weight = 2

[params]
  homepage_button_link = '/neighborhoods'
  homepage_button_text = 'kbh neighborhoods'
  homepage_intro = 'kph kærlighed is the Copenhagen guide organized around its beautiful and varied neigborhoods'
  homepage_image = 'https://images.unsplash.com/photo-1515749880686-7e4cc0909ff4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80'

  [params.homepage_meta_tags]
    meta_description = "kph kærlighed. The best that Copenhagen has to offer."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
